package com.learnlettersnumbers.app

import android.content.Context

/**
 * Audio validation for the offline TTS architecture.
 *
 * Spoken educational content is generated by an already-installed offline
 * Android TTS voice, so there are no bundled OGG resources to validate.
 */
object AudioCatalogValidator {
    fun validateOrThrow(context: Context) {
        // Intentionally empty: LocalAudioManager selects a non-network TTS voice.
    }
}
