package com.learnlettersnumbers.app

import android.content.Context

/** Audio validation for the offline TTS architecture. */
object AudioCatalogValidator {
    fun validateOrThrow(context: Context) {
        // Spoken content is generated by the installed offline Android TTS voice.
    }
}
